### PR TITLE
Add wraps to bugfix private cv layout

### PR DESCRIPTION
**Pull request by tuxinaut**
Add wraps to bugfix private cv layout

### CODE REVIEW

**Comment by tuxinaut** [comment]
How does it looks like?

**Comment by barraq** [comment]
@tuxinaut what do you mean? If you want to try the dev version of pandoc-moderncv just checkout the dev branch ;) https://github.com/barraq/pandoc-moderncv/tree/devel

**Comment by tuxinaut** [comment]
I'm confused you merged it into the dev branch and not in the master? Should I have missed the notification?

**Comment by barraq** [comment]
Indeed I merged it into the dev branch, it will be available in the next release (together with other features).

**Pull request closed without merging**
