### PR TITLE
Add support for patched wkhtmltopdf version

### PR DESCRIPTION
**Pull request by tuxinaut**
If you use a patched wkhtmltopdf version (archlinux https://aur.archlinux.org/packages/wkhtmltopdf-static/) for creating links. The standard options create a completely false pdf.

Sample pdf generations

Wrong

pdf_wrong

Right

pdf_right

### CODE REVIEW

**Comment by barraq** [comment]
Hi @tuxinaut thanks for this patch too. I'll add a small note in the Troubleshooting section of the README.md in order to inform other users that encounter the same issue. Also why are you using this "patched" static version? I am currious :)

**Comment by tuxinaut** [comment]
You are welcome. The standard version of wkhtmltopdf create **no** links e.g you can't open the link to my blog in the pdf file. You must copy the link go to the browser ....

In my opinion this is to much work for the person which takes a look at the cv.

**Comment by barraq** [comment]
Hummm ok I didn't know about this :) I checked that the pdf was well generated on both my OSx and Arch machines but I guess I didn't check the links on the one generated with `wkhtmltopdf`. The example pdf (http://barraq.github.io/pandoc-moderncv/preview/cv.pdf) was generated using wkpdf.

**Comment by tuxinaut** [comment]
And now you merge the Pull Request? :smile:

**Comment by barraq** [comment]
Before merging it I was testing it and it appears that the option `--print-media-type` is needed whatever the version of wkhtmltopdf you use. We therefore don't need to have a special case for the patched one or the classic one. I'll therefore remove the test `else ifeq ($(HTMLTOPDF),wkhtmltopdfpatched)` and merge it.

**Comment by barraq** [comment]
@tuxinaut this is now merged.

**Pull request closed without merging**
